### ISSUE TITLE
Add KTH SmarTS Lab's team to iTesla organization

### ISSUE THREAD

**Issue by lvanfretti** [itesla/ipsl#10]
@itesla I think you have to add my students and me to be members to the organization, I couldn't figure out a way to do that myself... the list is [here](https://github.com/orgs/SmarTS-Lab/people)

**Comment by MaximeBaudette** [comment]
@itesla 
Please only give write access to:
- Luigi
- Tin
- Me

I will explain to the others how to fork the repository and send pull requests for their contribution

**Comment by itesla** [comment]
Done

**Comment by MaximeBaudette** [comment]
@itesla 
I didn't notice earlier, but iTesla is a regular user account. 
Could you turn it into an organization so we can see the people's list like on our SmarTS lab:
https://github.com/SmarTS-Lab
