### ISSUE TITLE
Model Electrical/Events/Breaker.mo

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#138]
In model iPSL.Electrical.Events.Breaker.mo
do the pins **s** and **r** have to be connected in specific way?
For example, what pin should be connected to the element that will be disconnected?

**Comment by tinrabuzin** [comment]
@AIAitesla It doesn't matter how you connect them. If you use it with the generator, then only one of them is needed on the output and if you use it with the transformer then you need two on each of the sides of the transformer.

**Comment by AIAitesla** [comment]
@tinrabuzin Thank you!
