### ISSUE TITLE
Important to REN network: division by zero

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#141]
Hi @tinrabuzin,
working with the REN network we have found a division by zero in the model 
**iPSL.NonElectrical.Functions.SE**. 
For some regulators ESDC2A the parameters S_EE_1, S_EE_2, E1 and E2 are zero. As you can see in the following image, this goes to a 0 / 0.

![modelse](https://cloud.githubusercontent.com/assets/16029090/13492781/5992e882-e13a-11e5-843b-c430278eeccf.PNG)

Could you please protect the model for these input values? Thank you in advance!

**Comment by AIAitesla** [comment]
Hi @tinrabuzin,

could you please tell us which is the status of this issue?

Thank you!

**Comment by tinrabuzin** [comment]
@AIAitesla It's not done yet.
