### ISSUE TITLE
Models LOADPQ/LOADPQ_variation

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#146]
Hi @tinrabuzin,

We are updating a Modelica test system from Eurostag to the last version of the iPSL. In the older version of the library, this test system used the following model:  

**PowerSystems.Electrical.Loads.PwLoadwithVariation**.

We think that the equivalent model in the last library is:

**iPSL.Electrical.Loads.PSAT.LOADPQ_Variation**. 

We have tested the Modelica system from Eurostag with this LOADPQ_Variation but it doesn't work: the simulation stopped as you can see in the image above.

![image](https://cloud.githubusercontent.com/assets/16029090/13884219/57755b30-ed2d-11e5-8506-dbadf710bad9.png)
- Is this LOADPQ_Variation equivalent to PwLoadwithVariation? If so, could you please have a look at it?
- If you can't have a look, could you please recover the old PwLoadwithVariation model and put it in iPSL.Electrical.Loads.Eurostag package?

Thank you in advance.

**Comment by tinrabuzin** [comment]
@AIAitesla 

I'm not sure that this is the same model as the one from Eurostag. When we were cleaning the library we deleted the ones that were unsorted and duplicates. 

But in any case, it seems like there is a problem with something other than the load model, by looking at the figure attached. However, I cannot debug your problems without a test system that you're using. Can I have it?

**Comment by AIAitesla** [comment]
Hi @tinrabuzin,

we can't attach a Modelica file in the issue, so we will send it to you by e-mail.

The system we will send you is the test system A  and the library that you should use is the iPSL in AIAreverse branch. This test system used and simulated with model **PowerSystems.Electrical.Loads.PwLoadwithVariation** but does not simulate with **iPSL.Electrical.Loads.PSAT.LOADPQ_Variation**.

In the Modelica file there is the LOADPQ_variation and also (commented) the PwLoadwithVariation with the corresponding parameters. A part from this we also need that the model **iPSL.Electrical.Loads.PSAT.LOADPQ** will be reviewed because it is the only PQ load (excluding the load from PSSE).

Could you please have a look at these two models?

We also have noticed something it seems to be different in the initial P and Q units. These two models (LOADPQ and LOADPQ_variation) extend from the model baseLoad that extends from model **pfComponent** where P_0 and Q_0 are defined in MW and MVAr respectively. In the model LOADPQ_variation these two parameters are converted to p.u. but in the model LOADPQ they are in MW and MVAr because Sn and S_b are 100. In the image above you can see these differences.

![image](https://cloud.githubusercontent.com/assets/16029090/13924319/214d71f6-ef84-11e5-995f-4b1d44f58d0c.png)

Thank you very much for you help.

**Comment by tinrabuzin** [comment]
@AIAitesla 

Please, have a look at the new LOADPQ model.

**Comment by tinrabuzin** [comment]
@AIAitesla 

Also, I added the Eurostag model that you asked for.

**Comment by AIAitesla** [comment]
@tinrabuzin 
 we have tested the model :**iPSL.Electrical.Loads.PSAT.LOADPQ**, with the simple test SystA_iPSL and it does not work. 
There is not other LoadPQ model available in the iPSL, so we need this model to work.
Since, we are updating Eurostag models these models should be in the master and the AIAreverse branch. Please **merge them**

Thanks

**Comment by tinrabuzin** [comment]
@AIAitesla I will not merge them. I will just move the Eurostag model to the master branch.

By the way, if I put the Eurostag model back to the library, why do you even care about the PSAT loads? Maybe you should just use the ones that you've developed from Eurostag.

**Comment by tinrabuzin** [comment]
@AIAitesla 
In case you didn't know, it is possible to make the PSSE load to be constant power load.
Also, your system maybe doesn't work because of the too large disturbance to your system. Try increasing the fault impedance.

**Comment by AIAitesla** [comment]
Ok, sorry about the merge. It was an error to ask you . We will take care of that!

That was the question. We need to have Load models with PQ constant for Eurostag conversions. 
We haven't use PSS/E model because the PSAT model seems the more simple and appropriate for this, but if the PSS/E model is the one available for this then we will use it.

**Comment by tinrabuzin** [comment]
@AIAitesla 

As I said, if your system worked before with the Eurostag models and we added it now, it might be smart to just continue using it since there is not a lot of time until the end of the project...

**Comment by AIAitesla** [comment]
OK.
