### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#147]
Hi @tinrabuzin,

we have updated the models of the Eurostag machines and we are trying to push them to the iPSL but we get the following error:

![image](https://cloud.githubusercontent.com/assets/16029090/13917750/f6b820ba-ef62-11e5-9fc7-9e830ccee8f3.png)

Could you please have a look at it?
Thank you very much!

**Comment by tinrabuzin** [comment]
@AIAitelsa

Hi, 

I'm not sure but maybe @MaximeBaudette set the permissions such that you cannot pish directly. We decided to fork the lib and then creating pull requests. Try doing that.

**Comment by AIAitesla** [comment]
Hi @tinrabuzin, @MaximeBaudette, 

we get this error pushing changes in master or in AIAreverse branch.

**Comment by MaximeBaudette** [comment]
@tinrabuzin 
I did no such things
@AIAitesla 
We have been using the Fork / Pull request workflow for a while now. 
Please submit your changes as a pull request to the branch you intend to push to, we will review your changes and merge them.

**Comment by MaximeBaudette** [comment]
@AIAitesla 
Note: If you want direct push access, you can request that from Geoffroy, but I strongly advise you to follow the workflow we adopted.
