### ISSUE TITLE
please use semantic versioning

### ISSUE THREAD

**Issue by dietmarw** [itesla/ipsl#16]
The first release "v0.8" is unfortunately not following semantic versioning. Please change that to v0.8.0 and read http://semver.org/ on to why it is so important to always have the three levels. It is essential to follow that in order to be able to resolve dependencies and version conflicts. See also "[A follow-up paper Where impact got Going explained the new resolution algorithm used by impact to identify library dependencies](http://dx.doi.org/10.3384/ecp15118725)"

**Comment by MaximeBaudette** [comment]
Done !
Thanks for the assistance, I'll do the reading.
