### ISSUE TITLE
Add description to GitHub repo

### ISSUE THREAD

**Issue by dietmarw** [itesla/ipsl#17]
The iPSL GitHub repo is currently lacking a description. This description is used by impact (and impact search page) to display additional information. I've already added a description string to the modelica-3rdparty fork and you might want so simply copy that one or even be slightly more verbose,

**Comment by MaximeBaudette** [comment]
@geofjamg 
I didn't find the edit button, maybe it is because only admins can change the description (I'm not so familiar with Github, much more used to Bitbucket). 
Could you put:
"The iTesla Power System Library is a Modelica library developed as part of the iTesla project. The library contains a set of power system component models for phasor time domain simulations."

**Comment by geofjamg** [comment]
@MaximeBaudette You have been promoted as an iPSL team maintainer, so you can now do it by yourself.

**Comment by geofjamg** [comment]
The team is secret by default, do we switch to public one?

**Comment by MaximeBaudette** [comment]
@geofjamg 
I still didn't find the edit button for changing the description. 

as for public team, I don't see why not.

**Comment by geofjamg** [comment]
@MaximeBaudette you don't have an edit button just under the team name at https://github.com/orgs/itesla/teams/team-ipsl ?

**Comment by MaximeBaudette** [comment]
@geofjamg Yes I do, but I think @dietmarw referred to the description of the repository, not the team. 

![image](https://cloud.githubusercontent.com/assets/15156063/11033461/91c45fa8-86e3-11e5-8193-638af4821abe.png)

**Comment by MaximeBaudette** [comment]
Here is how it looks on the Rapid repository. 
I guess you should have such Edit button available. 

I don't need admin access to the repository, you can just paste the description I mentioned earlier. It is not something wee will change often, it just needs to be done once. 

![image](https://cloud.githubusercontent.com/assets/15156063/11033485/ca1286b4-86e3-11e5-969c-37e29b3989df.png)

**Comment by geofjamg** [comment]
@MaximeBaudette Ok. Done.

**Comment by dietmarw** [comment]
:+1:
