### ISSUE TITLE
Unsuitable type class

### ISSUE THREAD

**Issue by tbeu** [itesla/ipsl#18]
iPSL.Electrical.Branches.PwLine (and many more) is of type`class` but needs to be changed to a specialized class `model`.

**Comment by MaximeBaudette** [comment]
True, this will be corrected before v1.0.0

**Comment by dietmarw** [comment]
You can automatically close an issue via commit message by using one of the keywords mentioned in https://help.github.com/articles/closing-issues-via-commit-messages/ ;-)

**Comment by MaximeBaudette** [comment]
@dietmarw 
I know this, but somehow I strongly think that the most suited keyword is "closing".... This is not the first time I intend to close an issue by using "closing" instead of "closes" or any of the other keywords... I'll try to remember better for next time :-P
