### ISSUE TITLE
Package names do not match folder names (capitalization)

### ISSUE THREAD

**Issue by scottghiocel** [itesla/ipsl#2]
Loading the iPSL library in OpenModelica 1.9.2 produces errors due to mismatches between the name of the folder and the package files.  Renaming the folders to match the capitalization in the package name fixes the issue.  This produces the following errors:

[2] 13:50:15 Scripting Error
Failed to load package ipsl () using MODELICAPATH C:\Repository\Repos\ipsl\;C:/OpenModelica1.9.2/lib/omlibrary.

[3] 13:50:15 Grammar Error
[C:/Repository/Repos/ipsl/ipsl/package.mo: 2:1-28:9]: Expected the package to have name ipsl, but got iPSL.

This can be fixed by renaming the folder to match the capitalization in the package.mo file.

**Comment by lvanfretti** [comment]
@maximebaudette this is probably due to the decoupling process being done with Dymola and not OM.
I suggest we check the packages put together in Dymola with OM before every major commit.

**Comment by MaximeBaudette** [comment]
@lvanfretti I don't know why the names of the folder lost the capitalization on the version tht was uploaded here. In the version I provided, everything was fine. 
I can look into pushing a new version this weekend, directly from my computer to solve the issue

**Comment by lvanfretti** [comment]
@maximebaudette then maybe Geoffroy can look at this.

**Comment by scottghiocel** [comment]
FYI, this issue also applies to several packages within the iPSL package.  For example, see 'electrical' vs. 'Electrical', or 'psse' vs 'PSSE'.

**Comment by MaximeBaudette** [comment]
@scottghiocel I'll try to fix that over the weekend, by regenerating the whole package from Dymola.

**Comment by scottghiocel** [comment]
No hurry, I have it fixed on my end.  Just wanted to let you know.

**Comment by lvanfretti** [comment]
@scottghiocel if you have fixed it on your end, could you push your changes using GIT?

**Comment by scottghiocel** [comment]
Sourcetree on Windows did not recognize my folder renaming as a change that could be committed.  I will take a look next week.

**Comment by tinrabuzin** [comment]
I don't know why @itesla closed this issue but now it's resolved.
