### ISSUE TITLE
Problem with ESST1A pins

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#22]
In Model
IPSL.Electrical.Controls.PSSE.ES.ESST1A.ESST1A: 

1- the pin VUEL2 should be connected to a constant in REN-Systems.
Following KTH developpers this constant (see example IPSL.Examples.PSSE.Configuration.REN.RGroup1_1) have a value of -9999.
RTE recommends to put this value to zero.

2-  the imDerivativeLag model is not well initialized : pStartValue must be equal to Edf0
For this a ImPin EFD0 must be declared in the ESST1A model.

**Comment by tinrabuzin** [comment]
Would you care to explain why this should be 0? Did you have a look into the structure of ESST1A?

**Comment by AIAitesla** [comment]
Please ask RTE collaborator: @petitrenaudseb

**Comment by petitrenaudseb** [comment]
For this example (REN-Systems), VUEL2 is also connected to VUEL3 and VUEL1. In the ESST1A regulator, VUEL1 is used in the summator to calculate the error signal for the controller. If we use -9999 as input signal, the error integrate this input signal. It's better to use 0 .

**Comment by tinrabuzin** [comment]
Correct me if I'm wrong, but I don't see VUEL2 connected to VUEL3 and VUEL1? VUEL1 goes to summation block with VOTHSG and it should be 0. But VUEL2 and VUEL3 are connected to their respective HV gates. If you set them to 0 you basically limit the signal to 0 which, I guess, should not be the case.

**Comment by petitrenaudseb** [comment]
If you look at the ESST1A model, i agree with you, there is no connection between VUEL2, VUEL3, VUEL1. The signal should not be limited to 0 in all HV gates.

In the example quote by AIA, there is also no connection between VUEL2, VUEL3,VUEL1

But these connections appears in a more complete example created during the Itesla project about the REN network. 
With your comments, i verified the correction i want to made, and the better (correct me if you do not agree) is the following;
-> connect a constant equal to zero to VUEL1 (if there is no connection)
-> connect a constant equal to a low value (let's say -9999) to VUEL2 and VUEL3 (if there is no connection)

**Comment by tinrabuzin** [comment]
@petitrenaudseb I agree with you. The connections which you wrote are already implemented like this in the library's REN groups. I'll consider this issue closed now.

**Comment by MaximeBaudette** [comment]
@tinrabuzin @AIAitesla 
Following some discussion I had with people at RTE, it was decided that the network example (the more complex ones) will be integrated in this repository, as separate and individual packages. 
I will prepare the upload of the networks developed at KTH, so you can see how we decided to organize it. 

This means that REN_Groups and N44_Groups will be removed from the Example package of the library. I'll update you on how to proceed once I have prepared the examples and a wiki page to describe how to proceed.
