### ISSUE TITLE
Review equations machine GENROU

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#23]
In model

iPSL.Electrical.Machines.GENROU:

1- In the Genrou model, when EPDO is calculated, Xpd must be replaced by XPQ.
2- The sign of PSIppq0 must be changed for the calculation of Psiq0

**Comment by tinrabuzin** [comment]
@AIAitesla Those equations were written by Mengjia, so I'll have to spend some time with the manual and check if the suggestions are correct.

**Comment by MaximeBaudette** [comment]
@AIAitesla Can you enlighten us a bit more? I'll check the PSSE Manual, but if you already have it, please put a picture here.

@tinrabuzin I'll take care of this one, you are already busy with other stuff I want you to finish :smile:

**Comment by tinrabuzin** [comment]
@MaximeBaudette Tack för det! :)

**Comment by AIAitesla** [comment]
@MaximeBaudette these changes have been recommended by Sébastien.
@petitrenaudseb may you explain a bit more these changes in the equations to Maxime? Thanks!

**Comment by MaximeBaudette** [comment]
@AIAitesla I'm digging in Mengjia's rapport, I've found something for 1), and corrected it. 
I'll continue digging to see if I find something about 2) 
Are these mistakes only in GENROU, or in some other models as well?
