### ISSUE TITLE
Question about iPSL releases

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#28]
@MaximeBaudette  ¿Do you have a plan for next releases? For converting REN Systems we need to know when will the next release be ready and if you have a schedule for releases.
Please keep us up to date on the plan. Thanks!
AIA team.

**Comment by MaximeBaudette** [comment]
@AIAitesla 
I was trying to use the milestones to organize what should be done and in which order. 
For example, there is a pending milestones "Beta 2" that we intend to finish before the christmas holidays, @tinrabuzin is doing a lot for it. 
But we changed a bit how things are done, Releases use the Github built-in facility for releases using GIT tags (this "v0.8.0" that you can see https://github.com/itesla/ipsl/releases). 
So changes are more often committed to the master, and releases are now done with tags to follow the GitHub best practices. 

The plan of what will be fixed is basically in the issue tracking.

**Comment by AIAitesla** [comment]
Ok, thanks Maxime!
