### ISSUE TITLE
Input start value in the Derivative model

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#34]
In models
IPSL.Electrical.Controls.ES.ESST1A and IPSL.Electrical.Controls.ES.IEEEX1
- in the REN System @petitrenaudseb recommended the following:

"In the ESST1A model, the imDerivativeLag model is not well initialized : pStartValue must be equal to 
Edf0"

We have seen that you have changed the model imDerivativeLag to Modelica.Blocks.Continuous.Derivative. ¿Could you, please, have a look at this?

Thank you.

AIA team.

**Comment by tinrabuzin** [comment]
@AIAitesla @petitrenaudseb 

Model ImDerivativeLag has been removed from the library because the same model is available in the MSL (Modelica.Blocks.Continuous.Derviative). You're going to find the similar cases in a lot of other models also. 

Since we changed the model, now, output start value has to be defined instead of input so it is zero. Initialisation is not specified for ESST1A but for IEEEX1 it is. I fill fix the first one now.

**Comment by AIAitesla** [comment]
@tinrabuzin 
In any case the MSL (Modelica.Blocks.Continuous.Derviative) model the initialization should be y_start =Efd0.

Right?

**Comment by tinrabuzin** [comment]
No. It should be zero. Think about it derivative->steady-state-> output = 0.

**Comment by petitrenaudseb** [comment]
i agree with @tinrabuzin , y_start shoul be equal to zero, but x_start should be equal to Efd0

**Comment by tinrabuzin** [comment]
@petitrenaudseb Yes, you are right. I will have to update exciters.

**Comment by AIAitesla** [comment]
Since this issue is closed please @tinrabuzin  reopen it (this is the recommended action) and let us know when is done.

**Comment by AIAitesla** [comment]
This change is not yet in the master.
We are testing REN converted systems with the current version in the master branch and it would be nice to have it.
Thanks.

**Comment by tinrabuzin** [comment]
@AIAitesla 
I can do only a few things at the same time. 

I will soon push an update to the library with ESST1A and IEEEX1 that you use in the south system with this corrected. Also all of the models in the south system will be now validated.

**Comment by AIAitesla** [comment]
Ok. Thanks!
We are testing the South system with the master branch, so please let us know when the models are ready to test.
