### ISSUE TITLE
UVIG: General Discussion

### ISSUE THREAD

**Issue by lvanfretti** [itesla/ipsl#36]
For people interested in contributing towards the library, one important development task is the implementation and sw-to-sw validation of Generic and Domain-Specific-Tool models defined by the [Utility Variable-Generation Integration Group](http://uvig.org/newsroom/).

These modeles are widely used in two domain-specific-tools (PSS/E and PSLF). Yes, I know that there is an IEC Standard for these types of models, and I agree that we should implement and use IEC models. However, one of the most important goals of this library is that actual domain users (power system people) gains confidence in the model of our toolbox, and wether or not everyone likes it, it is a fact that the largest number of engineerings only trust domain-specific tools. Thus, if we are able, as we have done with other models (e.g. generators), we can build this trust with variable generator models that are available in domain-specific tools.

These are models are: http://www.uwig.org:8080/index.php?title=Main_Page
- Wind Turbines (WT): 
  -  [WT1](https://github.com/itesla/ipsl/issues/41)
  -  [WT2](https://github.com/itesla/ipsl/issues/42)
  -  [WT3](https://github.com/itesla/ipsl/issues/43)
  -  [WT4](https://github.com/itesla/ipsl/issues/44)
- Wind Power Plant [WPP](https://github.com/itesla/ipsl/issues/45)
- [PV Arrays](https://github.com/itesla/ipsl/issues/46)
- [PV Systems](https://github.com/itesla/ipsl/issues/47)
- [Distributed PV Generation](https://github.com/itesla/ipsl/issues/48)
- [Utility-Scale PV Generation](https://github.com/itesla/ipsl/issues/49)

So, anyone willing to contribute to the library doing development, you can start with the link above. It is very useful if you have experience and can carry out validation against PSS/E or PSLF to develop the model, but it is not strictly necessary. @tinrabuzin is developing a compliance checker that creates a PSS/E model from the Modelica model and this allows for automated validation.

If you are willing to help, please get in touch with @MaximeBaudette or @tinrabuzin who can tell you which ones we at SmarTS Lab think are most urgent to get done from different feedback received.

**Comment by MaximeBaudette** [comment]
@lvanfretti 
I have broken down this into separate issues and grouped them using a Milestone for the UVIG models. 
I think this way it would be easier to plan, as each models gets its discussion area in its own issue. 
All the issues are there: 
https://github.com/itesla/ipsl/milestones/Models%20from%20Utility%20Variable-Generation%20Integration%20Group

If you don't see any problems with that I will be closing this issue

**Comment by lvanfretti** [comment]
Keep issue open for general discussion

**Comment by lvanfretti** [comment]
I am closing this item as we will not continue to support iPSL within my team.
