### ISSUE TITLE
Test Networks developed at KTH SmarTS Lab

### ISSUE THREAD

**Issue by lvanfretti** [itesla/ipsl#4]
@tinrabuzin we need to upload the test networks we have developed over time.

There are several of them, I think some of them are already in the development examples, however, we could create under examples a folder called test networks with the network models (from what I remember, include):
- [x] SMIB (ref Kundur Book / PSAT)
- [x] 2 Area system (ref ?)
- [x] IEEE 9 Bus (ref PSAT)
- [x] IEEE 14 Bus (ref PSAT)
- [x] Nordic44 (ref PSSE)
- [ ] KTH Nordic 32 (ref Simulink)
- [ ] KTH Nordic 32 (ref PSAT)
- [ ] System A (ref Eurostag)
- [ ] System B (ref Eurostag)
- [x] AKD (Giussepe)
- [ ] AKA (Giussepe)
- [ ] HSD (Giussepe)
- [ ] iGrGen (Tetiana)
- [ ] Other small systems from Tetiana
- [ ] Norwegian distribution network (Ahsan)
- [ ] Models developed by Ahsan to replicate those in Yuwa's thesis

Let's try to track what is available of larger test networks, and see if I forgot something.

**Important**
- [ ] Create another repo with source files of each test system for Development and Application examples including the files from the source software used to develop them.

**New**
- [ ] Replicate all test models from PSAT (Ahsan)

**Comment by lvanfretti** [comment]
More systems:
- AKD (Giussepe)
- AKA (Giussepe)
- HSD (Giussepe)

**Comment by MaximeBaudette** [comment]
@lvanfretti 
I propose that we create a separate repository for all these test systems, so we don't mix it with the library. 
We can host it on the SmarTS-Lab organization.

**Comment by lvanfretti** [comment]
@MaximeBaudette 
I don't like that idea because if it is not in the /itesla/ipsl repo it will not be part of the distro, and therefore will not be maintained.

This is a major issue for the future, when I don't have any students to help me maintain the models... I don't want people to have to go through the same effort that we had to go through.

**Comment by MaximeBaudette** [comment]
@lvanfretti 
We can also host it on the itesla account but in a different repository.

**Comment by lvanfretti** [comment]
@MaximeBaudette 
Talk to Geoffrey to check what will be taken care of by iTesla consortium and what doesn't. 
But this is anyway confusing to new users. Why should it not be in the library? Every other library includes the examples with the library.

**Comment by lvanfretti** [comment]
@MaximeBaudette see the comment [here](https://github.com/itesla/ipsl/issues/3#issuecomment-154578069)

**Comment by MaximeBaudette** [comment]
@lvanfretti 
My point is that this repository should be dedicated to the library only. I personally think that other, more complex, networks should be developed as independent packages. And because of this I think it is more suitable to host our more complex networks on a separate repository. 
We have examples in the library, but I think we should only keep the examples that have been used for small scale validation.

**Comment by MaximeBaudette** [comment]
The Networks are being uploaded in the ApplicationExamples branch. Preliminary version of the some systems have been uploaded, I updated Luigi's comment with clickable list.

When the first batch of networks has been checked and validated, it will be merged into the master branch.

**Comment by lvanfretti** [comment]
@MaximeBaudette @tinrabuzin and Ahsan you have updated and validated a lot of test systems.

However, we don't provide access to validation files in the reference software. This is not part of iPSL, however, we should make them available somewhere.

I suggest we figure out a way of having them available. As I don't know GIT very well, I don't know if we can have another master branch with this, but we should edit the models with an annotation of where to find them, while preserving both the Development Examples and Application Examples structure.

**Comment by MaximeBaudette** [comment]
@lvanfretti 
Git is really not made to store large files. To give you an idea, Bitbucket limits the repository at 100 MB and GitHub 1Go, this translate in very few validation cases that we could store there before reaching the limit (one validation case is 10-50 MB depending on network size). 
I have some idea about how to do that and requested Tin to start thinking about it. 
I put down some of my ideas over there: 
https://trello.com/c/IQ9o6RAO

**Comment by lvanfretti** [comment]
But Maxime, we should not have so much storage needed!
The files we need to store, from PSAT, PSS/E and Eurotrash are more or less
only a few KB of size.
We don't need to store the output results.

In any case, this is really important to give people access to. We can't
claim that the system is "sw-to-sw validated" unless the source files are
available for anyone to reproduce the result.

And finally, if I have to pay cash to get a larger Github for SmarTS Lab,
we do it, even if I have to pay from my pocket.

Have a nice sunday!

**Comment by MaximeBaudette** [comment]
I think we should store the output results, so that we may in the future have an automatic validation of the library (I talked to Tin about Continuous Integration a while ago), and for this it would be more practical to just have all the "trace" of the models to run scripts. (It seems really unnecessary to have to "re-run all simulations", if we would have to run the check at every push)

As for the source files of the reference systems, we could collect them in a separate repository... But I'm afraid we might run into the problem of copyright holders. For a lot of these systems we are not the copyright holder, and then it makes it complicated to just collect the files, while keeping it clear, what is ours, and what is somebody else's.

**Comment by MaximeBaudette** [comment]
@lvanfretti you can ping ahsan like this @ahsanKTH

**Comment by tinrabuzin** [comment]
@MaximeBaudette @lvanfretti Here you can find an interesting way of testing the library - https://github.com/lbl-srg/modelica-buildings/wiki/Unit-Tests. I guess we could do the same with our DevelopmentExample and Application Examples... Though this doesn't solve the issue of the data storage.

**Comment by dietmarw** [comment]
Regarding storing simulation results you might wanna have a look at https://git-lfs.github.com/

**Comment by tinrabuzin** [comment]
@dietmarw Thanks for the tip! GIT LFS looks nice. 
I have another question. Have you ever seen that the automatic tests have been run on the Modelica code when it has been committed to the repository? Actually, do you have any suggestions about how we could check that our test systems still work correctly when someone makes changes to the repo?

**Comment by dietmarw** [comment]
@tinrabuzin I don't have much experience with automatic library testing tbh. I knew about the Buildings library having some pre-release scripts in place. But you might be able to use some of the setup that OpenModelica is using for its library coverage tests. But better hear with them :-)

**Comment by petitrenaudseb** [comment]
We could also you something like Jenkins https://jenkins-ci.org/ which is adapted for automatic build, test, etc.

You could use it to test if the latest commit is still ok and everything works after every commit or every night for example

**Comment by tinrabuzin** [comment]
@petitrenaudseb Yes, I've seen Jenkins and looked into Travis, but I'm not sure how I would do it for Modelica code.

**Comment by dietmarw** [comment]
For the ModelicaBook (which utilises OpenModelica for generation of plots etc.) @xie-dongping did recently implement a CI build using circleci (could probably be done with travis too I guess). Have a look at the setup: https://github.com/xogeny/ModelicaBook/blob/master/circle.yml which basically just launches the docker container: https://github.com/xogeny/ModelicaBook/tree/master/docker

**Comment by lvanfretti** [comment]
I am closing this item as we will not continue to support iPSL within my team.
