### ISSUE TITLE
UVIG: Distributed PV generation

### ISSUE THREAD

**Issue by MaximeBaudette** [itesla/ipsl#48]
Implementation and sw-to-sw validation of Generic and Domain-Specific-Tool models defined by the Utility Variable-Generation Integration Group.

**source**:  http://www.uwig.org:8080/index.php?title=Main_Page

It is very useful if you have experience and can carry out validation against PSS/E or PSLF to develop the model.

**Comment by lvanfretti** [comment]
I am closing this item as we will not continue to support iPSL within my team.
