### ISSUE TITLE
Unit error in angles inside Bus model

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#51]
After searching in all models used in REN system we found the problem that prevent the system from initializing.

In iPSL.Electrical.Buses.Bus
It says that the parameter angle_0 is giving in degrees - "Voltage angle (deg)"

And in the PwPin, the real (vr) and imaginary (vi) part of the voltage is using "cos" and "sin" functions from Modelica that work with the argument in radians.

Then, you should add the conversion to radians in the PwPin to start=V_0*cos(angle_0 \* pi / 180) and the same for imaginary part.

**Comment by tinrabuzin** [comment]
@AIAitesla Feel free to change it and create a pull request.

**Comment by MaximeBaudette** [comment]
@tinrabuzin I'm on it already :-P
