### ISSUE TITLE
Removed Eurostag Load

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#58]
@MaximeBaudette 
For the conversion from Eurostag we used the following model (in the old library)      PowerSystems.Electrical.Loads.PwLoadVoltageDependence that consider alpha and beta parameters in its equations but you have removed it.

We need this model (with alpha, beta parameters) for the conversion from Eurostag so you could put it in a folder called Eurostag.

**Comment by MaximeBaudette** [comment]
@AIAitesla I don't remember touching any of the Eurostag models. 
But you're welcome to add such folder with the load model coded as you need and send the pull request.

**Comment by AIAitesla** [comment]
@MaximeBaudette  This Load is one of the loads removed in the First Public Release v0.8.0.  This model wasn't in a Eurostag package, we used it for conversion from Eurostag.
Ok, we will add this model and send the pull request

**Comment by MaximeBaudette** [comment]
@AIAitesla 
but isn't the same model as Loads.PSAT.VoltDependant ?

**Comment by AIAitesla** [comment]
@MaximeBaudette It seems to be the same but when we test the Eurostag systems with the last release of the iPSL we will add the removed load if necessary. Thank you.

**Comment by MaximeBaudette** [comment]
@AIAitesla 
Just one note, I noticed an error common to all PSAT load models related to the per unit system, the conversion are wrong, it is badly done and results in error of the load values. 

I will fix the PSAT loads by tomorrow evening, so they have good equations.

**Comment by petitrenaudseb** [comment]
@MaximeBaudette
One question : as this model is a common model used in PSAT or Eurostag, should it stay under PSAT directory ? (behind this question, i think there is a general question around common model used by several software)

**Comment by MaximeBaudette** [comment]
@petitrenaudseb 
We haven't faced the case before... so we really have to think about it. 
In the current structure, we have used package names to indicate the original software, but it is also a way of indicating against which software the component was validated! 

Therefore, before moving anything out of these packages, we should discuss how to indicate in the model annotations that the model has been validated and against which software. We have started investigating it with @tinrabuzin, and discussed several alternatives, but we're open to suggestions. 

We looked into using  vendor specific annotations using ____IPSL(    ). The interest would be to be able to access this information via scripting for us. 
Maybe it is worth looking into one of the existing issues ( #29 ?) or a new issue to discuss this.

**Comment by MaximeBaudette** [comment]
@petitrenaudseb @AIAitesla 
In short, if AIA really needs that model for now, I would prefer for the time being that we have two models in the lib., one under /PSAT and one under /Eurostag, even if these two are almost equivalent.

**Comment by petitrenaudseb** [comment]
@MaximeBaudette 
Ok it's a good approach for a short term release to duplicate models , one by software

But for the long term, it's better to avoid duplicating code. 
Moreover i think we should discuss how to be sure that every evolution is correct and should be validate with comparison with the original software (nighty build, software to software validation, etc..)

**Comment by MaximeBaudette** [comment]
@petitrenaudseb 
That's the main reason why we want to find a way of documenting the validation that is accessible with scripts. We would like to have a more automatic validation check (at least for every release). 
The vendor specific annotations seem to fulfill this requirement, but @tinrabuzin and me are in unknown ground about it...

**Comment by AIAitesla** [comment]
@MaximeBaudette @petitrenaudseb 
Ok, then we will add the Eurostag folder with the Load model (just the one model we are using right now) and do a pull request.
Thanks
