### ISSUE TITLE
KundurSMIB 

### ISSUE THREAD

**Issue by MaximeBaudette** [itesla/ipsl#59]
Task list for the KundurSMIB system:
- [x] Create the case with constant Efd 
- [x] Store simulation settings in the models
- [x] Validate models against PSAT ref

**Comment by janlav** [comment]
- [x] plop

**Comment by MaximeBaudette** [comment]
Modelica doesn't allow what I wanted to do with the data record, so I give up the idea

**Comment by dietmarw** [comment]
And what exactly was it you wanted?

**Comment by MaximeBaudette** [comment]
I wanted to build something like a struct in Matlab, to store the parametrisation of a model. But I didn't succeed. Modelica was complaining about redefinitions, when some parameters have the same name. 

I would like to have a single record that can store a lot of parameters in the following structure. 
record.compo1.param1
record.compo1.param2
record.compo2.param1
record.compo2.param2
record.compo3.param1
record.compo3.param2

**Comment by dietmarw** [comment]
You mean as in `Modelica.Electrical.Machines.Utilities.ParameterRecords.InductionMachineData`? You can also nest records within records. But if in doubt (i.e., before giving up ;-)) asking on http://stackoverflow.com/questions/tagged/modelica often helps

**Comment by MaximeBaudette** [comment]
Something like that, but in the case where several parameters have the same name. 
I tried nesting records, but then I could not access all the parameter list from the top layer's GUI. 
I guess I could find a workaround to have that parameter list organized as I wish, but it would only be at the cost of user friendliness.

**Comment by tinrabuzin** [comment]
@MaximeBaudette We have a CSV file with some of the results from the PSAT. I can add it to the repo along with the model if you want.

**Comment by lvanfretti** [comment]
Shouldn't you close this issue now? I think the model works great! @tinrabuzin

**Comment by tinrabuzin** [comment]
@lvanfretti It was @MaximeBaudette who took it over from me. I'm not sure what is the current status of this but I have a plan to include it in the tutorial. We were also thinking about writing the tutorial in wiki...

**Comment by lvanfretti** [comment]
@tinrabuzin I'm not sure I want to put our tutorial on the wiki as a priority right now, you can see my other email on the new task that we should focus on for free time...

**Comment by MaximeBaudette** [comment]
you're right @lvanfretti, I finished the models, and made all the validation, it can be closed
