### ISSUE TITLE
Modification in PSS2A to remove initial oscillations in REN Network

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#64]
Hi @MaximeBaudette, 
@petitrenaudseb recommended us to do some changes in model **iPSL.Electrical.Controls.PSS.PSS2A.PSS2A**
to remove some initial oscillations in REN South network.
1. Add V_S20 real parameter
2. Add a real input: PMECH0
3. Add an initial equation.

You can see these changes in the atteched image.

![pss2a_changes](https://cloud.githubusercontent.com/assets/16029090/11930347/f6731e24-a7e2-11e5-8f48-6211221025a2.PNG)

**Comment by tinrabuzin** [comment]
@AIAitesla @petitrenaudseb 
These changes do not change the behaviour of PSS2A in any way. You only add additional parameter and change its value without using it anywhere in the code.

**Comment by AIAitesla** [comment]
@tinrabuzin 
There description was not complete, sorry. This parameter must be used as start value for washout_2:

Modelica.Blocks.Continuous.TransferFunction Washout2(
    b={1,0},
    initType=Modelica.Blocks.Types.Init.InitialOutput,
    y_start=V_S20,
    a={1,1/T_w2})

Please be aware that these equations are from old model of PSS2A.

**Comment by tinrabuzin** [comment]
@AIAitesla @petitrenaudseb 
Still, I disagree with the changes. First of all, it is a washout filter and, thus it's starting output value should be zero in steady state.

Your suggestions are probably based on the old implementation of the washout filter where the starting input value of the tf was needed and output.

**Comment by AIAitesla** [comment]
Ok @tinrabuzin we are testing the new PSS2A with tf in the REN South system and we will contact you in case we have problems.
