### ISSUE TITLE
Clean up the HTML of the documentation

### ISSUE THREAD

**Issue by dietmarw** [itesla/ipsl#65]
The current version contains a series of illegal HTML artefacts. Most of probably caused by the tool writing out illegal HTML entities (HTML is case sensitive).

Sine iPSL is now listed as 3rd-party Modelica library this also means that the OpenModelica project runs a documentation generation script in order to generate the [iPSL's online documentation](https://build.openmodelica.org/Documentation/iPSL.html). As you will notice it currently looks rather strange because of the illegal HTML named above. Luckily the documentation generator also runs a tidy script to check for HTML flaws from time to time. The result can be  checked in https://build.openmodelica.org/Documentation/tidy.filtered 
That file lists the flaws of **all** libraries. So simply search for "iPSL" to find your "TODO list" :smiley:

**Comment by MaximeBaudette** [comment]
@dietmarw 
In order to check the progress that we make on this issue, could you tell me what version this online checker is using for the automatic documentation generation:
- Latest commit on master branch?
- Latest release?

**Comment by dietmarw** [comment]
@sjoelund knows better. I guess master.

**Comment by sjoelund** [comment]
The [source](https://github.com/OpenModelica/OMLibraries/blob/master/repos.json) says master branch is followed.

**Comment by MaximeBaudette** [comment]
ok great ! thanks for the info... we will clean those HTMl artifacts very soon
