### ISSUE TITLE
Correction of initial equation in ESST1A model

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#74]
After revision of REN SOUTH System by @tinrabuzin 

There is a 1.23 value in IFD0 in the initial equation of ESST1A model:

initial equation 
  Efd0 = EFD0;
  IFD0 = 1.23;
  VA0 = Efd0 + K_LR \* (IFD0 - I_LR);
  VREF = VA0 / K_A + V_0;

This should be replaced by

initial equation 
  Efd0 = EFD0;
  IFD0 = XADIFD;
  VA0 = Efd0 + K_LR \* (IFD0 - I_LR);
  VREF = VA0 / K_A + V_0;

**Comment by tinrabuzin** [comment]
This is already corrected by commit:
SHA: 349dc8ef04eb47bbd98d8ba4228373da0b1162f4 
I'll close the issue now.
