### ISSUE TITLE
Adding Pin PMECH0 to TGOV1 model 

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#75]
After revision of REN SOUTH system by @tinrabuzin 

An input PMECH0 should be added to TGOV1

This will imply to remove connection PMECH-PMECH0 between generator and TGOV1 and connect
only PMECH0-PMECH0 in the automatic conversion.

**Comment by tinrabuzin** [comment]
You misunderstood me. What I wrote was, if you have a turbine governor at the generator you must not connect gen.PMECH0 to gen.PMECH. That has nothing to do with the addition of PMECH0. It was you connecting things in the wrong way. 

Another thing is me adding tgov.PMECH0. I will do this just to simplify initialisation of the governor.

**Comment by AIAitesla** [comment]
Ok. The removal of connection is clear.

But should we connect tgov.PMECH0 to generator.PMECH0 or not?

**Comment by tinrabuzin** [comment]
Yes, but I have to update the model first. I will let you know here.

**Comment by tinrabuzin** [comment]
@AIAitesla I updated TGOV1 as we discussed. I forgot to add that, since we added PMECH0, there is no longer need for parameter P0.
