### ISSUE TITLE
Parameters = 0 not accepted by Transfer functions in PSS2A model

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#76]
This issue is related to #33 and #39 

@tinrabuzin There are still problems with 0 value parameters in transfer functions "washout_{1,2,3,4}"

Inside Transfer function model from the Modelica library, the following equation give a division by zero, since a[1]=0:

 parameter Real d = bb[1]/a[1];

**Comment by tinrabuzin** [comment]
@AIAitesla 
0 is now accepted by PSS2A. I'll close the issue now.
