### ISSUE TITLE
Initialization of the PSSE model HYGOV results in division by zero in openmodelica

### ISSUE THREAD

**Issue by Hofsmo** [itesla/ipsl#78]
Hi,
I tried running the HYGOV PSSE development example in openmodelica. Unfortunately it crashed because HYGOV.G is zero, which results in division by zero. I fixed this by adding one more initial equation where I set G := g0. This fixes the initializtion.

I decided to not create a pull request since I am not certain whether or not this was the best way to solve the problem.

**Comment by tinrabuzin** [comment]
@Hofsmo 
Can you try it with the latest commit in master?

**Comment by Hofsmo** [comment]
It works. Many thanks.
