### ISSUE TITLE
Coherence in units for Model LOADPQ from PSAT folder 

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#80]
@tinrabuzin 

We are using model LOADPQ from PSAT package in Loads and this model extent to BaseClasses.baseLoad and iPSL.Electrical.Essentials.pfComponent where the angle is defined in radians (in baseLoad) and in degrees (in pfComponent) respectively.

Even if this does not seem to affect directly LOADPQ, it could affect other models depending on baselLoad, so it would be wise to check and correct this.

**Comment by MaximeBaudette** [comment]
@AIAitesla 
I marked this issue as duplicate in reference to #52. 
I initiated the conversation so we can all agree on a set of units to use for parameters / variables. If we come to an agreement this can then be implemented everywhere in the same manner. 

If you don't object, I will close this issue

**Comment by AIAitesla** [comment]
We agree with you @MaximeBaudette. It is a good idea to implement it everywhere in the same manner.
Feel free to close this issue.
