### ISSUE TITLE
WT4G1 connection schema

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#87]
@tinrabuzin we are working in a system with wind turbines and we don't know how to connect the following pins in model **iPSL.Electrical.Wind.PSSE.WT4G.WT4G1**:
- Real input **I_qcmd**
- Real input **I_pmcd**

What pin or constant value should be connected to them?

Thanks!

**Comment by tinrabuzin** [comment]
@AIAitesla 

One reason why I pushed the development example is because you can have a look at how those pins are connected there. 

It should be like this:
- i_qcmd - i_qcmd0
- i_pcmd - i_pcmd0
