### ISSUE TITLE
N44. Model SCRX

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#89]
@tinrabuzin  In Modelica model **iPSL.Electrical.Controls.PSSE.ES.SCRX.SCRX** the parameter C_SWITCH is declared as a boolean while in PSS/E this parameter can take values 0.0 or 1.0 (double value).

We can cast this value from double to boolean in the conversion. 
But it would be better to have the same type of parameter in Modelica an PSS/E because an external user will not have access to the conversion code.

Please, can you change this parameter in the model?

**Comment by tinrabuzin** [comment]
It won't be exactly the elegant solution to change this. It'll just unnecessary complicate the model. 

I'm afraid I don't understand what does access to conversion code have to do with casting parameters. If it's absolute must, then I'll do it.

**Comment by AIAitesla** [comment]
Ok. We will do the cast from double to boolean in the converter. 
The only thing to keep in mind is that the user will see:
- In PSS/E a double parameter value.
- In Modelica a boolean parameter value.

**Comment by tinrabuzin** [comment]
@AIAitesla 
The name is pretty self-explanatory (SWITCH) so I think it'll be fine. Thanks!
