### ISSUE TITLE
N44. Model IEESGO

### ISSUE THREAD

**Issue by AIAitesla** [itesla/ipsl#90]
@tinrabuzin Reviewing the system Nordic 44 (working with an earlier version of the iPSL) in order to have it working with the last version of the library we have seen the following.

In model **iPSL.Electrical.Controls.PSSE.TG.IEESGO** the imSimpleLag1 has the parameter **T_4** as input. This parameter is 0.3 in PSS/E file but in the model **iPSL.NonElectrical.Continuous.SimpleLag** this results in a division 0/0.

The error that we get in Dymola is:

_Error: Scalar system is always singular for reg_ieesgo__78bb0400_86f5_11e4_824f_c8f73332c8f4.imSimpleLag1.u = ((if abs(reg_ieesgo__78bb0400_86f5_11e4_824f_c8f73332c8f4.imSimpleLag1.T) <= 1E-015 then 0.0 else reg_ieesgo__78bb0400_86f5_11e4_824f_c8f73332c8f4.imSimpleLag1.state)-reg_ieesgo__78bb0400_86f5_11e4_824)/( -(if abs(reg_ieesgo__78bb0400_86f5_11e4_824f_c8f73332c8f4.imSimpleLag1.T) <= 1E-015 then reg_ieesgo__78bb0400_86f5_11e4_824f_c8f73332c8f4.imSimpleLag1.K else 0.0)) = 0/-0_

Please, could you have a look on this? Thanks!

**Comment by tinrabuzin** [comment]
Can you tell me what are your exact parameter settings for the whole model. Whatever I try in my test case, the system simulates.

**Comment by AIAitesla** [comment]
I have seen your Development example for the IEESGO model but it does not check.

The parameters for one of the IEESGO models in the Nordic 44 are:
- T_1 = 0.01,
- T_2 = 0.0,
- T_3 = 0.15,
- T_4 = 0.3,
- T_5 = 8.0,
- T_6 = 0.4,
- K_1 = 0.0,
- K_2 = 0.7,
- K_3 = 0.43,
- P_MAX = 1.0,
- P_MIN = 0.0

**Comment by tinrabuzin** [comment]
That's because it was an old development example. I'll update it now.

**Comment by tinrabuzin** [comment]
I made an example with those settings and the system simulates.

**Comment by AIAitesla** [comment]
Ok @tinrabuzin , maybe the issue is in the N44 connections. I'll see your example and let you know if I have any question about it. Thank you!

**Comment by tinrabuzin** [comment]
@AIAitesla 
Keep in mind that I didn't exactly replicate the connections as they are in the N44. I just used the IEESGO with your parameters and the excitation system is not the same. But, I don't think that should be the problem.

**Comment by AIAitesla** [comment]
@tinrabuzin We have updated the Nordic 44 to the new iPSL using the connection in your example to te IEESGO model and it simulates as well as the Nordic 44 with the old library version. Thank you for your help.
